/*
 * Human Review
 * And API for manipulating Thread Indicator documents in STIX format
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package gov.dhs.nppd.api;

import gov.dhs.nppd.ApiException;
import gov.dhs.nppd.model.APIOptionsResultList;
import gov.dhs.nppd.model.ListOfHumanReviewItems;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
@Ignore
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void humanreviewPendingGetTest() throws ApiException {
        ListOfHumanReviewItems response = api.humanreviewPendingGet();

        // TODO: test validations
    }
    
    /**
     * Return endpoint API documents
     *
     * When requested, this endpoint/verb combination returns documentation explainin how this API endpoint works
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void humanreviewPendingOptionsTest() throws ApiException {
        APIOptionsResultList response = api.humanreviewPendingOptions();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * update to support individual review
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void humanreviewStixIdFieldPutTest() throws ApiException {
        String stixId = null;
        String field = null;
        String value = null;
        api.humanreviewStixIdFieldPut(stixId, field, value);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void humanreviewStixIdPutTest() throws ApiException {
        String stixId = null;
        api.humanreviewStixIdPut(stixId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void userPutTest() throws ApiException {
        String username = null;
        String password = null;
        String response = api.userPut(username, password);

        // TODO: test validations
    }
    
}
