/*
 * Human Review
 * And API for manipulating Thread Indicator documents in STIX format
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package gov.dhs.nppd.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import gov.dhs.nppd.model.APIOptionsVerb;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * APIOptionsResultList
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2018-10-09T14:31:29.263-04:00[America/New_York]")
public class APIOptionsResultList {
  public static final String SERIALIZED_NAME_P_O_S_T = "POST";
  @SerializedName(SERIALIZED_NAME_P_O_S_T)
  private APIOptionsVerb POST = null;

  public static final String SERIALIZED_NAME_G_E_T = "GET";
  @SerializedName(SERIALIZED_NAME_G_E_T)
  private APIOptionsVerb GET = null;

  public static final String SERIALIZED_NAME_P_U_T = "PUT";
  @SerializedName(SERIALIZED_NAME_P_U_T)
  private APIOptionsVerb PUT = null;

  public static final String SERIALIZED_NAME_D_E_L_E_T_E = "DELETE";
  @SerializedName(SERIALIZED_NAME_D_E_L_E_T_E)
  private APIOptionsVerb DELETE = null;

  public static final String SERIALIZED_NAME_O_P_T_I_O_N_S = "OPTIONS";
  @SerializedName(SERIALIZED_NAME_O_P_T_I_O_N_S)
  private APIOptionsVerb OPTIONS = null;

  public APIOptionsResultList POST(APIOptionsVerb POST) {
    this.POST = POST;
    return this;
  }

   /**
   * Get POST
   * @return POST
  **/
  @ApiModelProperty(value = "")
  public APIOptionsVerb getPOST() {
    return POST;
  }

  public void setPOST(APIOptionsVerb POST) {
    this.POST = POST;
  }

  public APIOptionsResultList GET(APIOptionsVerb GET) {
    this.GET = GET;
    return this;
  }

   /**
   * Get GET
   * @return GET
  **/
  @ApiModelProperty(value = "")
  public APIOptionsVerb getGET() {
    return GET;
  }

  public void setGET(APIOptionsVerb GET) {
    this.GET = GET;
  }

  public APIOptionsResultList PUT(APIOptionsVerb PUT) {
    this.PUT = PUT;
    return this;
  }

   /**
   * Get PUT
   * @return PUT
  **/
  @ApiModelProperty(value = "")
  public APIOptionsVerb getPUT() {
    return PUT;
  }

  public void setPUT(APIOptionsVerb PUT) {
    this.PUT = PUT;
  }

  public APIOptionsResultList DELETE(APIOptionsVerb DELETE) {
    this.DELETE = DELETE;
    return this;
  }

   /**
   * Get DELETE
   * @return DELETE
  **/
  @ApiModelProperty(value = "")
  public APIOptionsVerb getDELETE() {
    return DELETE;
  }

  public void setDELETE(APIOptionsVerb DELETE) {
    this.DELETE = DELETE;
  }

  public APIOptionsResultList OPTIONS(APIOptionsVerb OPTIONS) {
    this.OPTIONS = OPTIONS;
    return this;
  }

   /**
   * Get OPTIONS
   * @return OPTIONS
  **/
  @ApiModelProperty(value = "")
  public APIOptionsVerb getOPTIONS() {
    return OPTIONS;
  }

  public void setOPTIONS(APIOptionsVerb OPTIONS) {
    this.OPTIONS = OPTIONS;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    APIOptionsResultList apIOptionsResultList = (APIOptionsResultList) o;
    return Objects.equals(this.POST, apIOptionsResultList.POST) &&
        Objects.equals(this.GET, apIOptionsResultList.GET) &&
        Objects.equals(this.PUT, apIOptionsResultList.PUT) &&
        Objects.equals(this.DELETE, apIOptionsResultList.DELETE) &&
        Objects.equals(this.OPTIONS, apIOptionsResultList.OPTIONS);
  }

  @Override
  public int hashCode() {
    return Objects.hash(POST, GET, PUT, DELETE, OPTIONS);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APIOptionsResultList {\n");
    
    sb.append("    POST: ").append(toIndentedString(POST)).append("\n");
    sb.append("    GET: ").append(toIndentedString(GET)).append("\n");
    sb.append("    PUT: ").append(toIndentedString(PUT)).append("\n");
    sb.append("    DELETE: ").append(toIndentedString(DELETE)).append("\n");
    sb.append("    OPTIONS: ").append(toIndentedString(OPTIONS)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

