/*
 * Human Review
 * And API for manipulating Thread Indicator documents in STIX format
 *
 * OpenAPI spec version: 1.0.0
 * Contact: deven.phillips@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * a hr field is being updated
 */
@ApiModel(description = "a hr field is being updated")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2018-10-11T15:52:26.790-04:00[America/New_York]")
public class FieldUpdatePutBody {
  public static final String SERIALIZED_NAME_ORIGINAL_VALUE = "original_value";
  @SerializedName(SERIALIZED_NAME_ORIGINAL_VALUE)
  private String originalValue = null;

  public static final String SERIALIZED_NAME_ACCEPTED_VALUE = "accepted_value";
  @SerializedName(SERIALIZED_NAME_ACCEPTED_VALUE)
  private String acceptedValue = null;

  public static final String SERIALIZED_NAME_FIELD_NAME = "field_name";
  @SerializedName(SERIALIZED_NAME_FIELD_NAME)
  private String fieldName = null;

  public static final String SERIALIZED_NAME_ACTION_TYPE = "action_type";
  @SerializedName(SERIALIZED_NAME_ACTION_TYPE)
  private String actionType = null;

  public FieldUpdatePutBody originalValue(String originalValue) {
    this.originalValue = originalValue;
    return this;
  }

   /**
   * Get originalValue
   * @return originalValue
  **/
  @ApiModelProperty(required = true, value = "")
  public String getOriginalValue() {
    return originalValue;
  }

  public void setOriginalValue(String originalValue) {
    this.originalValue = originalValue;
  }

  public FieldUpdatePutBody acceptedValue(String acceptedValue) {
    this.acceptedValue = acceptedValue;
    return this;
  }

   /**
   * Get acceptedValue
   * @return acceptedValue
  **/
  @ApiModelProperty(required = true, value = "")
  public String getAcceptedValue() {
    return acceptedValue;
  }

  public void setAcceptedValue(String acceptedValue) {
    this.acceptedValue = acceptedValue;
  }

  public FieldUpdatePutBody fieldName(String fieldName) {
    this.fieldName = fieldName;
    return this;
  }

   /**
   * Get fieldName
   * @return fieldName
  **/
  @ApiModelProperty(required = true, value = "")
  public String getFieldName() {
    return fieldName;
  }

  public void setFieldName(String fieldName) {
    this.fieldName = fieldName;
  }

  public FieldUpdatePutBody actionType(String actionType) {
    this.actionType = actionType;
    return this;
  }

   /**
   * Get actionType
   * @return actionType
  **/
  @ApiModelProperty(required = true, value = "")
  public String getActionType() {
    return actionType;
  }

  public void setActionType(String actionType) {
    this.actionType = actionType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FieldUpdatePutBody fieldUpdatePutBody = (FieldUpdatePutBody) o;
    return Objects.equals(this.originalValue, fieldUpdatePutBody.originalValue) &&
        Objects.equals(this.acceptedValue, fieldUpdatePutBody.acceptedValue) &&
        Objects.equals(this.fieldName, fieldUpdatePutBody.fieldName) &&
        Objects.equals(this.actionType, fieldUpdatePutBody.actionType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(originalValue, acceptedValue, fieldName, actionType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FieldUpdatePutBody {\n");
    
    sb.append("    originalValue: ").append(toIndentedString(originalValue)).append("\n");
    sb.append("    acceptedValue: ").append(toIndentedString(acceptedValue)).append("\n");
    sb.append("    fieldName: ").append(toIndentedString(fieldName)).append("\n");
    sb.append("    actionType: ").append(toIndentedString(actionType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

